---
project: helloworld2
default-region: eu-west-1
apps:
  - gordon.contrib.utils
  - himachine

dynamodb:
  test_dynamo_integration:
    lambda: himachine.hellopy
    #stream: arn:aws:dynamodb:eu-west-1:936837623851:table/test/stream/2015-11-09T10:53:25.441
    stream: ref://DynamoIntegrationArn
    batch_size: 1
    starting_position: LATEST

kinesis:
  test_kinesis_integration:
    lambda: himachine.hellopy
    stream: arn:aws:kinesis:eu-west-1:936837623851:stream/test
    batch_size: 1
    starting_position: LATEST


# api:
#   default:
#     /hello/{parameter}/:
#       lambda: simple.functions.hello_world
#       method: GET
#       methods:
#         - GET
#         - POST
#       stage:
#       security:

#
# logs:
#   - lambda: simple.functions.hello_world
#     group: ???
#     filter: ???
#     pattern: ???
#
# cognito_sync:
#   - lambda: ???
#     pool: ???
#
#
# kinesis:
#   - lambda: ???
#     stream: ???
#     batch_size: ???
#     starting_position: ???
#
# s3:
#   - lambda: ???
#     bucket: ???
#     event: ???
#     prefix: ???
#     suffix: ???
#
# scheduled:
#   - lambda: ???
#     name: ???
#     description: ???
#     expression: ???
#
# sns:
#   - lambda: ???
#     topic: ???
